# Generated by Django 6.0.1 on 2026-02-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100, verbose_name='Назавание продукта')),
                ('weight', models.FloatField(verbose_name='Количество(кг)')),
                ('fast', models.BooleanField(verbose_name='Срочность')),
                ('aggre_or_disagree', models.BooleanField(null=True, verbose_name='Согласие')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'applications',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenses', models.PositiveIntegerField(verbose_name='Затраты')),
                ('purchases', models.PositiveIntegerField(verbose_name='Покупки учеников')),
                ('income', models.PositiveIntegerField(verbose_name='Доход')),
            ],
            options={
                'verbose_name': 'Доход',
                'verbose_name_plural': 'Доходы',
                'db_table': 'income',
            },
        ),
    ]
