# Generated by Django 6.0.1 on 2026-02-08 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Назавание')),
                ('count1', models.PositiveIntegerField(verbose_name='Количество дней')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фотография')),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Набор',
                'verbose_name_plural': 'Наборы',
                'db_table': 'box',
            },
        ),
        migrations.CreateModel(
            name='BuyBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назавание')),
                ('count1', models.PositiveIntegerField(verbose_name='Количество дней')),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость')),
                ('created_at', models.DateTimeField()),
                ('end_box', models.DateTimeField()),
                ('created_at_lunch', models.DateField(blank=True, null=True)),
                ('created_at_breakfast', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Купленные наборы',
                'verbose_name_plural': 'Купленные наборы',
                'db_table': 'buybox',
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Назавание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фотография')),
                ('structure', models.CharField(max_length=150, unique=None, verbose_name='Состав')),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость')),
                ('breakfast_or_lunch', models.CharField(max_length=10, verbose_name='Тип: завтрак или обед')),
                ('fish', models.BooleanField(default=False, verbose_name='Аллерген на рыбу')),
                ('chicken', models.BooleanField(default=False, verbose_name='Аллерген на курицу')),
                ('lactose', models.BooleanField(default=False, verbose_name='Аллерген на лактозу')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('created_at', models.DateTimeField(verbose_name='Дата оценки')),
            ],
            options={
                'verbose_name': 'Комментарии',
                'verbose_name_plural': 'Комментарии',
                'db_table': 'rating',
            },
        ),
    ]
