# Generated by Django 6.0.1 on 2026-02-08 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.CharField(max_length=150, verbose_name='Состав заказа')),
                ('ready', models.BooleanField(default=False, verbose_name='Готов/нет')),
                ('take_order', models.BooleanField(default=False, verbose_name='Забран ли')),
                ('priceAll', models.PositiveIntegerField(verbose_name='Стоимость')),
                ('count1', models.PositiveIntegerField(verbose_name='Количество')),
                ('breakfast_or_lunch', models.CharField(max_length=10, verbose_name='Тип: завтрак или обед')),
                ('created_at', models.DateTimeField()),
                ('boxORnot', models.BooleanField(default=False, verbose_name='Набор ли')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('breakfast_or_lunch1', models.CharField(max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.catalog')),
            ],
        ),
    ]
